#!/bin/bash
git branch -d develop
git branch -d errorInTest
git branch -d test
git branch -d testing/mergeBranchTest

git checkout -b develop
git checkout -b errorInTest
git checkout -b test
git checkout -b testing/mergeBranchTest
git checkout -b master
git checkout -b master
git push -u origin --all
git checkout master